#ifndef LCD_H
#define LCD_H

#include "main.h"

/*
 * Simple LCD1602 Driver (HD44780) for STM32 using 4-bit mode.
 * This header exposes the public API used by user code:
 *  - LCD_Init()
 *  - LCD_Clear()
 *  - LCD_SetCursor(col, row)
 *  - LCD_Print(string)
 *  - LCD_WriteChar(c)
 *
 * Pin mapping is taken automatically from main.h
 * generated by CubeMX (LCD_RS_Pin, LCD_E_Pin, etc.)
 */

void LCD_Init(void);
void LCD_Clear(void);
void LCD_SetCursor(uint8_t col, uint8_t row);
void LCD_Print(const char *str);
void LCD_WriteChar(char c);
void LCD_PrintAt(uint8_t col, uint8_t row, const char *str);

#endif
